name: Build Application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt
        shell: cmd
        run: |
          if not exist C:\Qt mkdir C:\Qt
          python -m aqt install-qt windows desktop 6.3.0 win64_msvc2019_64 --outputdir C:\Qt --modules qtwebengine qtwebchannel qtpositioning

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Application
        shell: cmd
        run: .\build.bat

      - name: List Build Output
        run: dir build\Release\bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TinyTools-Release
          path: build/Release/bin/
